/* AUTO-GENERATED by `npm run generate:listing` from store/legal/*.md. Do not edit. */
import type { LegalDocKey } from './aboutInfo';

export interface LegalDoc {
  key: LegalDocKey;
  title: string;
  /** Canonical Markdown source, rendered in-app via parseMarkdownBlocks. */
  markdown: string;
}

export const LEGAL_DOCS: readonly LegalDoc[] = [
  { key: 'privacy', title: `Privacy Policy`, markdown: `# Levellio — Privacy Policy

**Effective date: June 19, 2026**

## The short version

Levellio is **local-first**: your habits, quests, and progress are stored **on
your device** by default. Some features are **optional and you choose them** — if
you create an account to use **Community Projects** and the community feed, that
activity is stored in our cloud backend (Google Firebase) so it can be shared
with the people you collaborate with. We (**Ethix Innova LLC**) do **not** use
advertising or third-party analytics SDKs, and we do **not** sell your data. If
you use a cloud AI model, you bring your own API key — it stays in your device's
secure keychain and is sent only to the AI provider you pick.

---

## 1. Who this policy covers

This policy applies to the Levellio mobile app ("the App") published by
**Ethix Innova LLC** (principal: Antonio Joel Tito, PhD) ("we", "us"). It explains what
information the App handles and how. It does not cover third-party services you
separately choose to use (such as an AI provider whose API key you supply, or the
app store you downloaded from), which are governed by their own policies.

## 2. Information the App handles

**Information you create — stored on your device.** Quests, habits, goals, notes,
XP, levels, streaks, your chosen hero, and app settings are saved locally on your
device using the operating system's standard app storage. By default this solo
data is **not** transmitted to us.

**Optional account — only if you create one.** Community features require a free
account. When you sign up we collect your **email address** and a **display name**
(you choose it) through **Google Firebase Authentication**. Your password is
handled by Firebase Authentication; we never see it.

**Community Projects & the community feed — only if you use them.** When you join
or create a Community Project, post, comment, react, or follow someone, that
content is stored in our cloud database (**Google Firebase / Firestore**) so it
can be shared with other members. This can include: your display name and chosen
hero look, the **habit titles you choose to share** to a project, your
contribution counts, the text of your **posts and comments**, your **reactions**,
who you **follow**, and your account identifier (uid). You control feed
visibility with the "Share my activity" toggle on each project.

**Optional location — off by default.** If you turn on "Capture location & speed"
in Settings, the App may attach where an activity happened to your logs and
confirm when a community-project habit was done **on-site**. This is **opt-in**,
requires the OS location permission, and can be turned off anytime.

**AI API keys — only if you opt in.** If you enable cloud AI suggestions, your
own API key is stored only in your device's secure keychain and used solely to
send your suggestion requests to the provider you choose. We never receive, store,
log, or transmit your key.

**No analytics or ads.** The App does not include third-party analytics,
attribution, or advertising SDKs, and does not build advertising profiles.

> The app store you installed from (Apple App Store or Google Play) may collect
> its own download, crash, and usage metrics under **its** policy, outside our
> control.

## 3. How information is used

Solo data is used only to run the App on your device. Account and community data
are used to operate the features you opt into: signing you in across devices,
running Community Projects, and showing the community feed and your network. We do
**not** use your information for advertising, profiling, or sale, and we do not
sell or share personal information with data brokers.

## 4. On-device vs. cloud AI

- **On-device suggestions (default).** Run locally and make **no network calls**.
- **Bring-your-own-key cloud AI (optional).** The suggestion text you submit is
  sent directly from your device to the third-party provider you selected (for
  example, Google Gemini, OpenAI, or Anthropic) using your own key. That
  provider's handling of your data is governed by **their** policy.

## 5. Third parties / processors

- **Google Firebase** (Authentication + Firestore) — processes your account and
  community/project data so those optional features work across devices. Google
  acts as our data processor; its handling is governed by Google's terms.
- **Your chosen AI provider** — only when you enable cloud AI with your own key.
- **Apple App Store / Google Play** — for app distribution and, if you allow it,
  store-level diagnostics.

## 6. Data storage, retention & deletion

- **Solo data** lives on your device — delete individual items in the App, use the
  in-app Danger Zone, or uninstall to remove it.
- **Your AI key** — clear it anytime in Settings.
- **Account & community data** — open **Settings → Account → Delete account** to
  permanently delete your account and remove your community + project data
  (memberships, contributions, posts, comments, reactions, and follows) from our
  cloud backend. You can also leave any individual project at any time.

We retain account and community data only while your account exists; deleting your
account removes it.

## 7. Security

Solo data uses your operating system's standard app storage; any AI key uses the
OS secure keychain. Account and community data are transmitted over encrypted
connections (HTTPS) to Google Firebase. No method of electronic storage is
perfectly secure; keep your device updated and protected.

## 8. Children's privacy

The App is not directed to children under 13 (or the minimum age required in your
country), and we do not knowingly collect personal information from children. If
you believe a child has created an account, contact us and we will delete it.

## 9. Your rights

You can access, correct, export, or delete your data: solo data directly on your
device (Section 6), and account/community data via in-app account deletion.
Depending on where you live (for example, under GDPR or CCPA/CPRA) you may have
additional rights; contact us (Section 11) and we will help.

## 10. Changes to this policy

We may update this policy as the App evolves. Material changes will be reflected
by a new effective date and, where appropriate, an in-app or store notice.

## 11. Contact

Questions about this policy? Contact **Ethix Innova LLC** at **doctortitoconsulting@gmail.com**.
` },
  { key: 'terms', title: `Terms of Service`, markdown: `# Levellio — Terms of Service

**Effective date: June 19, 2026**

## 1. Agreement to these terms

These Terms of Service ("Terms") govern your use of the Levellio mobile app
("the App") provided by **Ethix Innova LLC** (principal: Antonio Joel Tito, PhD) ("we", "us"). By downloading or using
the App, you agree to these Terms. If you do not agree, do not use the App. Your
use is also subject to the rules of the app store you downloaded from.

## 2. License

We grant you a personal, limited, non-exclusive, non-transferable, revocable
license to install and use the App on devices you own or control, for your own
personal, non-commercial use, subject to these Terms and the applicable app
store terms.

## 3. Acceptable use

You agree not to:

- copy, modify, distribute, sell, or lease any part of the App except as the law
  permits;
- reverse engineer or attempt to extract source code, except to the extent that
  applicable law expressly allows;
- use the App to break any law or to infringe anyone's rights;
- interfere with or disrupt the integrity or performance of the App;
- in community spaces, post content that is unlawful, hateful, harassing,
  threatening, deceptive, or that infringes others' rights, or impersonate anyone.

We may remove content or restrict access that violates these Terms.

## 4. Your content

The quests, habits, notes, and other content you create are yours. Solo content
is stored on your device; you are responsible for your own backups, and
uninstalling may permanently delete locally stored data.

If you create an optional account and use **Community Projects** or the community
feed, the content you choose to share (project memberships and contributions,
posts, comments, reactions, and who you follow) is stored in our cloud backend
and shown to other members. You are responsible for what you share, you grant
other members the ability to view it within the App, and you can delete it — leave
a project, or delete your account in **Settings → Account → Delete account**,
which removes your account and community/project data. Project owners manage their
own projects and invite codes; share invite codes only with people you trust.

## 4a. Location (optional)

If you enable location in Settings, the App may record where an activity happened
and confirm when a community-project habit was done on-site. This is optional and
can be turned off at any time.

## 5. Bring-your-own-key AI and third-party services

The App can optionally connect to a third-party AI provider using an API key
**you** supply. If you enable this:

- you are responsible for obtaining the key, for any fees the provider charges,
  and for complying with that provider's terms and policies;
- your requests are sent directly to the provider you choose, and their handling
  of your data is governed by their terms, not ours;
- we are not responsible for third-party services, their availability, outputs,
  costs, or changes.

## 6. AI output and "not professional advice" disclaimer

The App and any AI-generated suggestions are provided for general motivation and
organization only. They are **not** professional advice and are **not** a
substitute for medical, mental-health, financial, legal, fitness, or other
professional guidance. Do not rely on the App for decisions that require a
qualified professional. AI suggestions may be inaccurate, incomplete, or
unsuitable for you — use your own judgment, and consult a professional where
appropriate. If you may have a medical or mental-health concern, seek qualified
help; in an emergency, contact your local emergency services.

## 7. Intellectual property

The App, including its design, artwork, characters (such as the hero and Wisp),
text, and software, is owned by **Ethix Innova LLC** or its licensors and is protected
by intellectual-property laws. Except for the license in Section 2, no rights are
granted to you.

## 8. Purchases and subscriptions

The App's core habit-tracking features are free. Optional paid features, if and
when offered, will be sold through the applicable app store and are subject to
that store's payment, billing, renewal, and refund terms. Prices and the exact
contents of any paid plan will be disclosed at the point of purchase. **No paid
features are sold in this version.**

Our mission: when Levellio introduces paid features in the future, a portion of
the proceeds will support community health efforts in Fort Liberté, Haiti. This
is a statement of intent, not a fixed percentage, a charitable solicitation, or
a promise of any tax-deductible donation.

## 9. Disclaimer of warranties

The App is provided **"as is"** and **"as available,"** without warranties of
any kind, whether express or implied, including but not limited to implied
warranties of merchantability, fitness for a particular purpose, and
non-infringement. We do not warrant that the App will be uninterrupted,
error-free, secure, or that any data will be preserved. Some jurisdictions do not
allow the exclusion of certain warranties, so some of the above may not apply to
you.

## 10. Limitation of liability

To the maximum extent permitted by law, **Ethix Innova LLC** and its suppliers will
not be liable for any indirect, incidental, special, consequential, or punitive
damages, or for any loss of data, profits, or goodwill, arising out of or related
to your use of (or inability to use) the App, even if advised of the possibility
of such damages. To the maximum extent permitted by law, our total liability for
any claim relating to the App will not exceed the greater of the amount you paid
us for the App in the 12 months before the claim, or US $50. Some jurisdictions
do not allow certain limitations, so some of the above may not apply to you.

## 11. Indemnification

You agree to indemnify and hold harmless **Ethix Innova LLC** from any claims, losses,
liabilities, and expenses (including reasonable legal fees) arising from your
misuse of the App or your violation of these Terms or applicable law.

## 12. Termination

These Terms apply until terminated. Your license ends automatically if you breach
them; you may end it at any time by uninstalling the App. Sections that by their
nature should survive (for example, Sections 6, 7, 9, 10, and 11) survive
termination.

## 13. Governing law

These Terms are governed by the laws of **State of Texas, USA**, without regard
to its conflict-of-laws rules. The courts located in **State of Texas, USA** will
have jurisdiction, except where applicable law grants you the right to bring
proceedings in your local courts.

## 14. Changes to these terms

We may update these Terms as the App evolves. Material changes will be reflected
by a new effective date and, where appropriate, an in-app or store notice.
Continued use after changes take effect constitutes acceptance.

## 15. Contact

Questions about these Terms? Contact **Ethix Innova LLC** at **doctortitoconsulting@gmail.com**.
` },
];

export function getLegalDoc(key: LegalDocKey): LegalDoc {
  return LEGAL_DOCS.find((d) => d.key === key) ?? LEGAL_DOCS[0]!;
}
