/* AUTO-GENERATED by `npm run generate:listing` from store/legal/*.md. Do not edit. */
import type { LegalDocKey } from './aboutInfo';

export interface LegalDoc {
  key: LegalDocKey;
  title: string;
  /** Canonical Markdown source, rendered in-app via parseMarkdownBlocks. */
  markdown: string;
}

export const LEGAL_DOCS: readonly LegalDoc[] = [
  { key: 'privacy', title: `Privacy Policy`, markdown: `# Levellio — Privacy Policy

**Effective date: June 10, 2026**

## The short version

Levellio is **local-first**. Your habits, quests, and progress are stored **on
your device**. We (**Ethix Innova LLC**) do **not** operate a server that collects
your personal data, we do **not** require an account, and we do **not** use
advertising or third-party analytics SDKs. If you choose to use a cloud AI
model, you bring your own API key — it stays in your device's secure keychain
and is sent only to the AI provider you pick.

---

## 1. Who this policy covers

This policy applies to the Levellio mobile app ("the App") published by
**Ethix Innova LLC** (principal: Antonio Joel Tito, PhD) ("we", "us"). It explains what information the App handles and
how. It does not cover third-party services you separately choose to use (such
as an AI provider whose API key you supply, or the app store you downloaded
from), which are governed by their own policies.

## 2. Information the App handles

**Information you create — stored on your device.** Quests, habits, goals,
notes, XP, levels, streaks, your chosen hero, and app settings. This data is
saved locally on your device using the operating system's standard app storage.
It is not transmitted to us.

**AI API keys — only if you opt in.** If you enable cloud AI suggestions, you
enter your own API key for a provider you choose. The key is stored only in your
device's secure keychain (via the operating system's secure storage) and is used
solely to send your suggestion requests to that provider. We never receive,
store, log, or transmit your key to ourselves.

**No accounts.** The App does not require sign-up or login, and we do not collect
names, email addresses, phone numbers, contacts, precise location, photos, or
device advertising identifiers.

**No analytics or ads.** The App does not include third-party analytics,
attribution, or advertising SDKs, and does not build advertising profiles.

> The app store you installed from (Apple App Store or Google Play) may collect
> its own download, crash, and usage metrics under **its** policy, outside our
> control. Operating-system crash reporting applies only if you have enabled it
> at the OS level.

## 3. How information is used

Information you create is used only to run the App on your device — to show your
quests, track progress, calculate streaks and levels, and render your hero. If
you opt into cloud AI, your request text is sent to your chosen provider to
generate suggestions. We do not use your information for advertising, profiling,
or sale, and we do not sell or share personal information.

## 4. On-device vs. cloud AI

- **On-device suggestions (default).** Run locally and make **no network
  calls**. Your data does not leave the device.
- **Bring-your-own-key cloud AI (optional).** If you enable it, the suggestion
  text you submit is sent directly from your device to the third-party provider
  you selected (for example, Google Gemini, OpenAI, or Anthropic) using your own
  key. That provider's handling of your data is governed by **their** privacy
  policy and terms. Review them before enabling cloud AI.

## 5. Third parties

- **Your chosen AI provider** — only when you enable cloud AI with your own key.
- **Apple App Store / Google Play** — for app distribution and, if you allow it,
  store-level diagnostics.

We do not integrate any other third-party data processors. **Note:** the App's
codebase contains scaffolding for optional future cloud features (account
sign-in and cloud backup) that are **not active** and **collect no data** in this
version. If we activate them in a future release, we will update this policy and
the app store data disclosures before they go live.

## 6. Data storage, retention & deletion

Because your data lives on your device, **you control it**:

- **Delete specific items** — remove individual quests or habits in the App.
- **Remove your AI key** — clear it anytime in Settings; this deletes it from the
  secure keychain.
- **Delete everything** — uninstalling the App removes its locally stored data
  from your device. (If an in-app "reset" option is provided, it clears data
  immediately.)

We have no server-side copy of your data to retain or delete.

## 7. Security

Game data uses your operating system's standard app storage; any AI key uses the
OS secure keychain. No method of electronic storage is perfectly secure, but
because we do not transmit or centrally store your personal data, the main risks
are those affecting your own device. Keep your device updated and protected.

## 8. Children's privacy

The App is not directed to children under 13 (or the minimum age required in
your country), and we do not knowingly collect personal information from
children. Because the App collects no personal data on our servers, there is no
such data for us to access or delete. If you believe a child has provided
personal data through a third-party service you enabled, contact that service.

## 9. Your rights

We do not hold your personal data on our servers, so requests to access,
correct, export, or delete are fulfilled directly by you on your device (see
Section 6). Depending on where you live (for example, under GDPR or CCPA/CPRA),
you may have additional rights regarding any data a third-party provider or app
store processes on your behalf; direct those requests to the relevant provider.
For questions, contact us (Section 11).

## 10. Changes to this policy

We may update this policy as the App evolves (for example, if optional cloud
features are activated). Material changes will be reflected by a new effective
date and, where appropriate, an in-app or store notice.

## 11. Contact

Questions about this policy? Contact **Ethix Innova LLC** at **doctortitoconsulting@gmail.com**.
` },
  { key: 'terms', title: `Terms of Service`, markdown: `# Levellio — Terms of Service

**Effective date: June 10, 2026**

## 1. Agreement to these terms

These Terms of Service ("Terms") govern your use of the Levellio mobile app
("the App") provided by **Ethix Innova LLC** (principal: Antonio Joel Tito, PhD) ("we", "us"). By downloading or using
the App, you agree to these Terms. If you do not agree, do not use the App. Your
use is also subject to the rules of the app store you downloaded from.

## 2. License

We grant you a personal, limited, non-exclusive, non-transferable, revocable
license to install and use the App on devices you own or control, for your own
personal, non-commercial use, subject to these Terms and the applicable app
store terms.

## 3. Acceptable use

You agree not to:

- copy, modify, distribute, sell, or lease any part of the App except as the law
  permits;
- reverse engineer or attempt to extract source code, except to the extent that
  applicable law expressly allows;
- use the App to break any law or to infringe anyone's rights;
- interfere with or disrupt the integrity or performance of the App.

## 4. Your content

The quests, habits, notes, and other content you create are yours and are stored
on your device (see the Privacy Policy). You are responsible for your content and
for keeping your own backups; uninstalling the App may permanently delete locally
stored data.

## 5. Bring-your-own-key AI and third-party services

The App can optionally connect to a third-party AI provider using an API key
**you** supply. If you enable this:

- you are responsible for obtaining the key, for any fees the provider charges,
  and for complying with that provider's terms and policies;
- your requests are sent directly to the provider you choose, and their handling
  of your data is governed by their terms, not ours;
- we are not responsible for third-party services, their availability, outputs,
  costs, or changes.

## 6. AI output and "not professional advice" disclaimer

The App and any AI-generated suggestions are provided for general motivation and
organization only. They are **not** professional advice and are **not** a
substitute for medical, mental-health, financial, legal, fitness, or other
professional guidance. Do not rely on the App for decisions that require a
qualified professional. AI suggestions may be inaccurate, incomplete, or
unsuitable for you — use your own judgment, and consult a professional where
appropriate. If you may have a medical or mental-health concern, seek qualified
help; in an emergency, contact your local emergency services.

## 7. Intellectual property

The App, including its design, artwork, characters (such as the hero and Wisp),
text, and software, is owned by **Ethix Innova LLC** or its licensors and is protected
by intellectual-property laws. Except for the license in Section 2, no rights are
granted to you.

## 8. Purchases and subscriptions

The App's core habit-tracking features are free. Optional paid features, if and
when offered, will be sold through the applicable app store and are subject to
that store's payment, billing, renewal, and refund terms. Prices and the exact
contents of any paid plan will be disclosed at the point of purchase. **No paid
features are sold in this version.**

Our mission: when Levellio introduces paid features in the future, a portion of
the proceeds will support community health efforts in Fort Liberté, Haiti. This
is a statement of intent, not a fixed percentage, a charitable solicitation, or
a promise of any tax-deductible donation.

## 9. Disclaimer of warranties

The App is provided **"as is"** and **"as available,"** without warranties of
any kind, whether express or implied, including but not limited to implied
warranties of merchantability, fitness for a particular purpose, and
non-infringement. We do not warrant that the App will be uninterrupted,
error-free, secure, or that any data will be preserved. Some jurisdictions do not
allow the exclusion of certain warranties, so some of the above may not apply to
you.

## 10. Limitation of liability

To the maximum extent permitted by law, **Ethix Innova LLC** and its suppliers will
not be liable for any indirect, incidental, special, consequential, or punitive
damages, or for any loss of data, profits, or goodwill, arising out of or related
to your use of (or inability to use) the App, even if advised of the possibility
of such damages. To the maximum extent permitted by law, our total liability for
any claim relating to the App will not exceed the greater of the amount you paid
us for the App in the 12 months before the claim, or US $50. Some jurisdictions
do not allow certain limitations, so some of the above may not apply to you.

## 11. Indemnification

You agree to indemnify and hold harmless **Ethix Innova LLC** from any claims, losses,
liabilities, and expenses (including reasonable legal fees) arising from your
misuse of the App or your violation of these Terms or applicable law.

## 12. Termination

These Terms apply until terminated. Your license ends automatically if you breach
them; you may end it at any time by uninstalling the App. Sections that by their
nature should survive (for example, Sections 6, 7, 9, 10, and 11) survive
termination.

## 13. Governing law

These Terms are governed by the laws of **State of Texas, USA**, without regard
to its conflict-of-laws rules. The courts located in **State of Texas, USA** will
have jurisdiction, except where applicable law grants you the right to bring
proceedings in your local courts.

## 14. Changes to these terms

We may update these Terms as the App evolves. Material changes will be reflected
by a new effective date and, where appropriate, an in-app or store notice.
Continued use after changes take effect constitutes acceptance.

## 15. Contact

Questions about these Terms? Contact **Ethix Innova LLC** at **doctortitoconsulting@gmail.com**.
` },
];

export function getLegalDoc(key: LegalDocKey): LegalDoc {
  return LEGAL_DOCS.find((d) => d.key === key) ?? LEGAL_DOCS[0]!;
}
