/**
 * Generates Levellio's store-listing Markdown (from src/content/storeListing.ts)
 * and the printable legal HTML (from store/legal/*.md). Pure Node — runs on
 * Node's built-in TypeScript support (Node >= 22), no extra dependency.
 *
 *   npm run generate:listing
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  APPLE,
  checkFieldLengths,
  PLAY,
  RELEASE_NOTES_V1,
} from '../src/content/storeListing.ts';
import { renderHtmlDocument, renderMarkdown } from '../src/content/markdownLite.ts';

const root = process.cwd();
const listingDir = join(root, 'store', 'listing');
const legalDir = join(root, 'store', 'legal');

const GENERATED = '> Generated from source by `npm run generate:listing` — do not edit by hand.\n';

function write(path: string, body: string): void {
  writeFileSync(path, body.endsWith('\n') ? body : body + '\n', 'utf8');
  console.log(`  wrote ${path.replace(root + '/', '')}`);
}

// --- Apple App Store ---
write(
  join(listingDir, 'app-store.md'),
  `# Levellio — Apple App Store listing

${GENERATED}
## App name (≤30)

${APPLE.name}

## Subtitle (≤30)

${APPLE.subtitle}

## Promotional text (≤170)

${APPLE.promotionalText}

## Keywords (≤100 — comma-separated, no spaces)

${APPLE.keywords}

## Description

${APPLE.description}

---

## Also configure in App Store Connect

- **Primary category:** Health & Fitness · **Secondary:** Productivity _(suggested — confirm)_
- **Privacy Policy URL:** [HOSTED-PRIVACY-POLICY-URL] _(required — host \`store/legal/privacy-policy.html\`)_
- **Support URL / Marketing URL:** [YOUR-URLS]
- **Age rating:** complete the questionnaire (no objectionable content; not directed to children)
- **App Privacy / "Nutrition label":** see \`store/listing/data-disclosure.md\`
`,
);

// --- Google Play ---
write(
  join(listingDir, 'google-play.md'),
  `# Levellio — Google Play listing

${GENERATED}
## Title (≤30)

${PLAY.title}

## Short description (≤80)

${PLAY.shortDescription}

## Full description (≤4000)

${PLAY.fullDescription}

## Feature bullets (for graphics / highlights)

${PLAY.featureBullets.map((b) => `- ${b}`).join('\n')}

---

## Also configure in Play Console

- **Category:** Health & Fitness _(suggested — confirm)_
- **Privacy Policy URL:** [HOSTED-PRIVACY-POLICY-URL] _(required — host \`store/legal/privacy-policy.html\`)_
- **Data safety form:** see \`store/listing/data-disclosure.md\`
- **Content rating (IARC):** complete the questionnaire
`,
);

// --- Release notes ---
write(
  join(listingDir, 'release-notes.md'),
  `# Levellio — release notes

${GENERATED}
## v1.0.0

${RELEASE_NOTES_V1}
`,
);

// --- Live character-count compliance table ---
const rows = checkFieldLengths()
  .map((r) => `| ${r.label} | ${r.length} | ${r.limit} | ${r.ok ? '✅' : '❌ OVER'} |`)
  .join('\n');
write(
  join(listingDir, 'CHARACTER-COUNTS.md'),
  `# Levellio — store field character counts

${GENERATED}
| Field | Length | Limit | Status |
| --- | ---: | ---: | :---: |
${rows}
`,
);

// --- Legal: Markdown → printable HTML + in-app bundled content ---
const legalDocs: Array<{ slug: 'privacy-policy' | 'terms-of-service'; key: string; title: string; md: string }> = [
  { slug: 'privacy-policy', key: 'privacy', title: 'Privacy Policy', md: '' },
  { slug: 'terms-of-service', key: 'terms', title: 'Terms of Service', md: '' },
];
for (const doc of legalDocs) {
  doc.md = readFileSync(join(legalDir, `${doc.slug}.md`), 'utf8');
  write(
    join(legalDir, `${doc.slug}.html`),
    renderHtmlDocument(`Levellio — ${doc.title}`, renderMarkdown(doc.md)),
  );
}

// Emit a TS module so the app can render the legal docs in-app (offline, no WebView).
const tsLiteral = (s: string): string => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
write(
  join(root, 'src', 'content', 'legalContent.ts'),
  `/* AUTO-GENERATED by \`npm run generate:listing\` from store/legal/*.md. Do not edit. */
import type { LegalDocKey } from './aboutInfo';

export interface LegalDoc {
  key: LegalDocKey;
  title: string;
  /** Canonical Markdown source, rendered in-app via parseMarkdownBlocks. */
  markdown: string;
}

export const LEGAL_DOCS: readonly LegalDoc[] = [
${legalDocs.map((d) => `  { key: '${d.key}', title: ${tsLiteral(d.title)}, markdown: ${tsLiteral(d.md)} },`).join('\n')}
];

export function getLegalDoc(key: LegalDocKey): LegalDoc {
  return LEGAL_DOCS.find((d) => d.key === key) ?? LEGAL_DOCS[0]!;
}
`,
);

const over = checkFieldLengths().filter((r) => !r.ok);
if (over.length > 0) {
  console.error(`\n✖ ${over.length} field(s) exceed their limit.`);
  process.exit(1);
}
console.log('\nAll store fields within limits.');
